from pathlib import Path
import tempfile

DEFAULT_PROCESSING_LIMIT = 3
DEFAULT_DOWNLOAD_QUEUE_SIZE = 10
DEFAULT_DOWNLOAD_CACHE = (
    Path(tempfile.gettempdir()) / "processing-pipeline-download-cache"
)
DEFAULT_MAX_RETRIES = 3
DOWNLOAD_TIMEOUT = 30
SIMULATE_MIN_PROCESS_TIME = 5
SIMULATE_MAX_PROCESS_TIME = 10
DEFAULT_QUEUE_TIMEOUT = 1.0
NO_SLEEP_ENV_VAR = "PIPELINE_NO_SLEEP"
